{% set name = "wpextract" %}
{% set version = "1.0.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wpextract-{{ version }}.tar.gz
  sha256: 559290ca5813264ccb18be40df585478001b57372316e70cdc49460d4eb091fc

build:
  entry_points:
    - wpextract = wpextract.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<3.13
    - beautifulsoup4 >=4.12.0
    - langcodes >=3.3.0
    - lxml >=5.0.0
    - numpy >=1.23.0
    - pandas >=1.5.2
    - tqdm >=4.65.0
    - requests >=2.32.3
    - click >=8.0.1
    - click-option-group >=0.5.3

test:
  imports:
    - wpextract
  commands:
    - pip check
    - wpextract --help
  requires:
    - pip

about:
  summary: Create datasets from WordPress sites
  home: https://gatenlp.github.io/wpextract/
  dev_url: https://github.com/GateNLP/wpextract
  doc_url: https://gatenlp.github.io/wpextract/
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE
    - src/wpextract/download/ORIGINAL_LICENSE

extra:
  recipe-maintainers:
    - freddyheppell
