{% set name = "wpextract" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wpextract-{{ version }}.tar.gz
  sha256: c4a5abe330cb75d7032223a1a28af3cb643baa2661c7e6c5410f860b783f1fa0

build:
  entry_points:
    - wpextract = wpextract.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<3.13
    - beautifulsoup4 >=4.12.0
    - langcodes >=3.3.0
    - lxml >=5.0.0
    - numpy >=1.23.0
    - pandas >=1.5.2
    - tqdm >=4.65.0
    - requests >=2.32.3
    - click >=8.0.1
    - click-option-group >=0.5.3
    - urllib3 >1.21.3,<3

test:
  imports:
    - wpextract
  commands:
    - pip check
    - wpextract --help
  requires:
    - pip

about:
  summary: Create datasets from WordPress sites
  home: https://wpextract.readthedocs.io
  dev_url: https://github.com/GateNLP/wpextract
  doc_url: https://wpextract.readthedocs.io
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE
    - src/wpextract/download/ORIGINAL_LICENSE

extra:
  recipe-maintainers:
    - freddyheppell
