{% set name = "wpextract" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wpextract-{{ version }}.tar.gz
  sha256: 721a7a637a7b5876b73d616fd427444d9dc7a212daab056ed41bfe699560508c

build:
  entry_points:
    - wpextract = wpextract.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4 >=4.12.0
    - langcodes >=3.3.0
    - lxml >=5.0.0
    - numpy >=1.23.0
    - pandas >=1.5.2
    - tqdm >=4.65.0
    - requests >=2.32.3
    - click >=8.0.1
    - click-option-group >=0.5.3
    - urllib3 >1.21.3,<3

test:
  imports:
    - wpextract
  commands:
    - pip check
    - wpextract --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Create datasets from WordPress sites
  home: https://wpextract.readthedocs.io
  dev_url: https://github.com/GateNLP/wpextract
  doc_url: https://wpextract.readthedocs.io
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE
    - src/wpextract/download/ORIGINAL_LICENSE

extra:
  recipe-maintainers:
    - freddyheppell
